language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

sudo: false

install:
  - python setup.py install
  - pip install -U pytest coverage pytest-cov coveralls

script:
  - python setup.py test

after_success:
  - coveralls

